### ISSUE TITLE
`helm-gtags-update-tags` seems to be broken.

### ISSUE THREAD

**Issue by Fuco1** [syohex/emacs-helm-gtags#99]
When I call it, nothing apparent happens.  From time to time it fails with a message about a missing buffer `" *helm-gtags-update-tag*"`.  I usually create this manually with `get-buffer-create` to shut up that error.

However, tags still aren't recreated.

I'm using this over TRAMP, but that should not matter as calling shell is fully transparent.

**Comment by syohex** [comment]
Is this issue same as #96 ? I fixed it. `*helm-gtags-update-tag*` is no longer used.
Would you upgrade latest version and retry ?

**Comment by Fuco1** [comment]
Possibly. Will do, thanks.

**Comment by taurhine** [comment]
For those who are still having this problem: I've had this issue on Debian Jessie. As mentioned in  https://github.com/syohex/emacs-helm-gtags helm-gtags-update-tags only works when GNU Global version is 6.2.3 or higher.
